version: '3.8'

services:

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: db
    environment:
      SA_PASSWORD: "Admin12345"
      ACCEPT_EULA: "Y"
    volumes:
      - db_data:/var/opt/mssql
    networks:
      - backend_net

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - frontend_net
      - backend_net

  frontend:
    image: nginx
    container_name: frontend
    ports:
      - "80:80"
    networks:
      - frontend_net

networks:
  frontend_net:
  backend_net:

volumes:
  db_data:
