spring.datasource.url=jdbc:sqlserver://db:1433;databaseName=proyecto_db;encrypt=false;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=Admin12345

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
